http:
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: frontend
      priority: 1

    auth:
      rule: "PathPrefix(`/api/auth`)"
      entryPoints:
        - web
      service: auth-service
      priority: 10

    user:
      rule: "PathPrefix(`/api/users`)"
      entryPoints:
        - web
      service: user-service
      priority: 10

    inventory:
      rule: "PathPrefix(`/api/inventory`)"
      entryPoints:
        - web
      service: inventory-service
      priority: 10

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-proxy:8080"

    user-service:
      loadBalancer:
        servers:
          - url: "http://user-proxy:8080"

    inventory-service:
      loadBalancer:
        servers:
          - url: "http://inventory-proxy:8080"
