// WHY Protocol Buffers (.proto files)?
// This file is the CONTRACT between User Service and Inventory Service.
// Both services generate code from this file. If one side changes the
// contract, the other side fails to compile — catching breaking changes
// at build time, not at runtime.
//
// Compare to REST/JSON: you can send any JSON shape and it might
// work, might crash, might silently drop fields. Proto enforces
// the schema at the protocol level.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/inventory_user.proto

package inventorypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryGrpc_AssignStarterPack_FullMethodName = "/inventory.InventoryGrpc/AssignStarterPack"
)

// InventoryGrpcClient is the client API for InventoryGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryGrpc is the internal RPC service for inter-service calls.
// This is NOT exposed through the API gateway — only other services
// can call it. External clients use REST via the gateway.
type InventoryGrpcClient interface {
	AssignStarterPack(ctx context.Context, in *AssignStarterPackRequest, opts ...grpc.CallOption) (*AssignStarterPackResponse, error)
}

type inventoryGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryGrpcClient(cc grpc.ClientConnInterface) InventoryGrpcClient {
	return &inventoryGrpcClient{cc}
}

func (c *inventoryGrpcClient) AssignStarterPack(ctx context.Context, in *AssignStarterPackRequest, opts ...grpc.CallOption) (*AssignStarterPackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignStarterPackResponse)
	err := c.cc.Invoke(ctx, InventoryGrpc_AssignStarterPack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryGrpcServer is the server API for InventoryGrpc service.
// All implementations must embed UnimplementedInventoryGrpcServer
// for forward compatibility.
//
// InventoryGrpc is the internal RPC service for inter-service calls.
// This is NOT exposed through the API gateway — only other services
// can call it. External clients use REST via the gateway.
type InventoryGrpcServer interface {
	AssignStarterPack(context.Context, *AssignStarterPackRequest) (*AssignStarterPackResponse, error)
	mustEmbedUnimplementedInventoryGrpcServer()
}

// UnimplementedInventoryGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryGrpcServer struct{}

func (UnimplementedInventoryGrpcServer) AssignStarterPack(context.Context, *AssignStarterPackRequest) (*AssignStarterPackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignStarterPack not implemented")
}
func (UnimplementedInventoryGrpcServer) mustEmbedUnimplementedInventoryGrpcServer() {}
func (UnimplementedInventoryGrpcServer) testEmbeddedByValue()                       {}

// UnsafeInventoryGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryGrpcServer will
// result in compilation errors.
type UnsafeInventoryGrpcServer interface {
	mustEmbedUnimplementedInventoryGrpcServer()
}

func RegisterInventoryGrpcServer(s grpc.ServiceRegistrar, srv InventoryGrpcServer) {
	// If the following call panics, it indicates UnimplementedInventoryGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryGrpc_ServiceDesc, srv)
}

func _InventoryGrpc_AssignStarterPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignStarterPackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryGrpcServer).AssignStarterPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryGrpc_AssignStarterPack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryGrpcServer).AssignStarterPack(ctx, req.(*AssignStarterPackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryGrpc_ServiceDesc is the grpc.ServiceDesc for InventoryGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryGrpc",
	HandlerType: (*InventoryGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignStarterPack",
			Handler:    _InventoryGrpc_AssignStarterPack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory_user.proto",
}
