// WHY Protocol Buffers (.proto files)?
// This file is the CONTRACT between User Service and Inventory Service.
// Both services generate code from this file. If one side changes the
// contract, the other side fails to compile — catching breaking changes
// at build time, not at runtime.
//
// Compare to REST/JSON: you can send any JSON shape and it might
// work, might crash, might silently drop fields. Proto enforces
// the schema at the protocol level.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/inventory_user.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssignStarterPackRequest is sent by User Service when a user
// completes onboarding. The user_id identifies who gets the assets.
type AssignStarterPackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignStarterPackRequest) Reset() {
	*x = AssignStarterPackRequest{}
	mi := &file_proto_inventory_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignStarterPackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignStarterPackRequest) ProtoMessage() {}

func (x *AssignStarterPackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignStarterPackRequest.ProtoReflect.Descriptor instead.
func (*AssignStarterPackRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_user_proto_rawDescGZIP(), []int{0}
}

func (x *AssignStarterPackRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Asset represents a single assigned resource.
type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_proto_inventory_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_proto_inventory_user_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Asset) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// AssignStarterPackResponse contains all assets assigned to the user.
type AssignStarterPackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignStarterPackResponse) Reset() {
	*x = AssignStarterPackResponse{}
	mi := &file_proto_inventory_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignStarterPackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignStarterPackResponse) ProtoMessage() {}

func (x *AssignStarterPackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignStarterPackResponse.ProtoReflect.Descriptor instead.
func (*AssignStarterPackResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_user_proto_rawDescGZIP(), []int{2}
}

func (x *AssignStarterPackResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *AssignStarterPackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_inventory_user_proto protoreflect.FileDescriptor

const file_proto_inventory_user_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/inventory_user.proto\x12\tinventory\"3\n" +
	"\x18AssignStarterPackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"_\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"_\n" +
	"\x19AssignStarterPackResponse\x12(\n" +
	"\x06assets\x18\x01 \x03(\v2\x10.inventory.AssetR\x06assets\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2o\n" +
	"\rInventoryGrpc\x12^\n" +
	"\x11AssignStarterPack\x12#.inventory.AssignStarterPackRequest\x1a$.inventory.AssignStarterPackResponseB Z\x1euser-service/proto/inventorypbb\x06proto3"

var (
	file_proto_inventory_user_proto_rawDescOnce sync.Once
	file_proto_inventory_user_proto_rawDescData []byte
)

func file_proto_inventory_user_proto_rawDescGZIP() []byte {
	file_proto_inventory_user_proto_rawDescOnce.Do(func() {
		file_proto_inventory_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_user_proto_rawDesc), len(file_proto_inventory_user_proto_rawDesc)))
	})
	return file_proto_inventory_user_proto_rawDescData
}

var file_proto_inventory_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_inventory_user_proto_goTypes = []any{
	(*AssignStarterPackRequest)(nil),  // 0: inventory.AssignStarterPackRequest
	(*Asset)(nil),                     // 1: inventory.Asset
	(*AssignStarterPackResponse)(nil), // 2: inventory.AssignStarterPackResponse
}
var file_proto_inventory_user_proto_depIdxs = []int32{
	1, // 0: inventory.AssignStarterPackResponse.assets:type_name -> inventory.Asset
	0, // 1: inventory.InventoryGrpc.AssignStarterPack:input_type -> inventory.AssignStarterPackRequest
	2, // 2: inventory.InventoryGrpc.AssignStarterPack:output_type -> inventory.AssignStarterPackResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inventory_user_proto_init() }
func file_proto_inventory_user_proto_init() {
	if File_proto_inventory_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_user_proto_rawDesc), len(file_proto_inventory_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_user_proto_goTypes,
		DependencyIndexes: file_proto_inventory_user_proto_depIdxs,
		MessageInfos:      file_proto_inventory_user_proto_msgTypes,
	}.Build()
	File_proto_inventory_user_proto = out.File
	file_proto_inventory_user_proto_goTypes = nil
	file_proto_inventory_user_proto_depIdxs = nil
}
